### ISSUE TITLE
The sha in metadata.yaml does not match latest version of template.tpl

### ISSUE THREAD

**Issue by Zhankevich** [yumamur/Sugar-Model-Viewer-Tag#1]
While reviewing your request, we noticed that sha in metadata.yaml does not match latest version of template.tpl. Consider updating metadata.yaml.

**Comment by yumamur** [comment]
May I ask if I should hash the template.tpl or add the commit hash in metadata.yaml? I got a bit confused there

**Comment by Zhankevich** [comment]
It should be the commit hash. Sorry for the confusion.

**Comment by Zhankevich** [comment]
Looks good, thanks!
